find_package(OpenMP)
if (OPENMP_FOUND)
  message(STATUS "Found OpenMP")
else ()
  message(STATUS "Did not find OpenMP")
  set(VT_TV_OPENMP_ENABLED OFF)
endif()

function(link_openmp)
  if(VT_TV_OPENMP_ENABLED)
    target_link_libraries(${VT_TV_LIBRARY} PUBLIC OpenMP::OpenMP_CXX)
  endif()
endfunction()
