find_package(OpenMP)
if (OPENMP_FOUND)
  message(STATUS "Found OpenMP")
  set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${OpenMP_C_FLAGS}")
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${OpenMP_CXX_FLAGS}")
  set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} ${OpenMP_EXE_LINKER_FLAGS}")
else ()
  message(STATUS "Did not find OpenMP")
  set(VT_TV_OPENMP_ENABLED OFF)
endif()

function(link_openmp)
  if(VT_TV_OPENMP_ENABLED)
    target_link_libraries(${VT_TV_LIBRARY} PUBLIC OpenMP::OpenMP_CXX)
  endif()
endfunction()
